//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuni
    {
        public int ID { get; set; }
        public Nullable<int> CODCOMUNE { get; set; }
        public Nullable<int> IDPROV { get; set; }
        public string DESCCOMUNE { get; set; }
        public string SGLNAZIONALE { get; set; }
        public string SGLCATASTALE { get; set; }
        public string CAP { get; set; }
        public Nullable<int> FLGVARIAZIONE { get; set; }
        public string DTVARIAZIONE { get; set; }
        public Nullable<int> ordine { get; set; }
    }
}
