//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbZohoEntities : DbContext
    {
        public DbZohoEntities()
            : base("name=DbZohoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Utenti> Utenti { get; set; }
        public virtual DbSet<tokens> tokens { get; set; }
        public virtual DbSet<Ordini> Ordini { get; set; }
        public virtual DbSet<T_Corriere> T_Corriere { get; set; }
        public virtual DbSet<T_listinobase> T_listinobase { get; set; }
        public virtual DbSet<OrderZoho> OrderZoho { get; set; }
        public virtual DbSet<PriceListZoho> PriceListZoho { get; set; }
        public virtual DbSet<UserZoho> UserZoho { get; set; }
        public virtual DbSet<Nazioni> Nazioni { get; set; }
        public virtual DbSet<Comuni> Comuni { get; set; }
        public virtual DbSet<Province> Province { get; set; }
    }
}
