//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbZohoEntities : DbContext
    {
        public DbZohoEntities()
            : base("name=DbZohoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Utenti> Utenti { get; set; }
        public virtual DbSet<tokens> tokens { get; set; }
        public virtual DbSet<Ordini> Ordini { get; set; }
        public virtual DbSet<T_Corriere> T_Corriere { get; set; }
        public virtual DbSet<T_listinobase> T_listinobase { get; set; }
    }
}
