//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nazioni
    {
        public int IdNazione { get; set; }
        public string Nazione { get; set; }
        public string Code { get; set; }
        public Nullable<int> IdGruppo { get; set; }
    }
}
