//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordini
    {
        public int IdOrdine { get; set; }
        public Nullable<int> IdUt { get; set; }
        public Nullable<int> IdListinoBase { get; set; }
        public Nullable<int> IdOrdineInt { get; set; }
        public Nullable<int> IdIndirizzo { get; set; }
        public Nullable<int> IdCorriere { get; set; }
        public Nullable<int> TipoConsegna { get; set; }
        public Nullable<System.DateTime> DataIns { get; set; }
        public Nullable<System.DateTime> DataCambioStato { get; set; }
        public Nullable<System.DateTime> DataPrevProduzione { get; set; }
        public Nullable<System.DateTime> DataPrevConsegna { get; set; }
        public string Annotazioni { get; set; }
        public Nullable<int> Nfogli { get; set; }
        public Nullable<int> Preventivo { get; set; }
        public string Anteprima { get; set; }
        public string SorgenteFronte { get; set; }
        public string SorgenteRetro { get; set; }
        public string SorgenteCopertina { get; set; }
        public Nullable<int> TipoRetro { get; set; }
        public Nullable<decimal> PrezzoCalcolatoNetto { get; set; }
        public Nullable<decimal> PrezzoCorriere { get; set; }
        public Nullable<decimal> TotaleNetto { get; set; }
        public Nullable<decimal> TotaleIva { get; set; }
        public Nullable<decimal> TotaleOrdine { get; set; }
        public Nullable<int> Qta { get; set; }
        public Nullable<int> NumeroColli { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<int> Altezza { get; set; }
        public Nullable<int> Larghezza { get; set; }
        public Nullable<float> Mq { get; set; }
        public Nullable<int> Stato { get; set; }
        public Nullable<int> StatoWeb { get; set; }
        public string Lavorazioni { get; set; }
        public Nullable<bool> OrdineWeb { get; set; }
        public Nullable<int> IdCons { get; set; }
        public Nullable<int> InseritoDa { get; set; }
        public Nullable<int> Profondita { get; set; }
        public Nullable<int> IdTipoFustella { get; set; }
        public Nullable<int> IdCoupon { get; set; }
        public Nullable<decimal> Sconto { get; set; }
        public Nullable<decimal> Ricarico { get; set; }
        public string NomeLavoro { get; set; }
        public Nullable<int> Orientamento { get; set; }
        public Nullable<int> NoEmailDemone { get; set; }
        public Nullable<int> OrdineInOmaggio { get; set; }
        public string ExtraData { get; set; }
        public Nullable<int> IdPromo { get; set; }
        public Nullable<int> UsaNomeLavoroInFattura { get; set; }
        public Nullable<int> IdMailPreventivo { get; set; }
        public Nullable<int> IdMacchinarioProduzioneUtilizzato { get; set; }
        public Nullable<System.DateTime> ConsegnaGarantita { get; set; }
        public Nullable<int> ConsegnaGarantitaDa { get; set; }
    
        public virtual T_Corriere T_Corriere { get; set; }
        public virtual T_listinobase T_listinobase { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
