//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Corriere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Corriere()
        {
            this.Ordini = new HashSet<Ordini>();
        }
    
        public int IdCorriere { get; set; }
        public string Descrizione { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> GGConsegna { get; set; }
        public string TestoMail { get; set; }
        public string NomeBreve { get; set; }
        public bool PrevedeAccorpamento { get; set; }
        public Nullable<int> TipoCorriere { get; set; }
        public Nullable<int> PercPortoAssegnato { get; set; }
        public Nullable<int> KgLimite1 { get; set; }
        public Nullable<decimal> TariffaLimite1 { get; set; }
        public Nullable<int> KgLimite2 { get; set; }
        public Nullable<decimal> TariffaLimite2 { get; set; }
        public Nullable<int> KgLimite3 { get; set; }
        public Nullable<decimal> TariffaLimite3 { get; set; }
        public Nullable<int> KgLimite4 { get; set; }
        public Nullable<decimal> TariffaLimite4 { get; set; }
        public Nullable<int> KgLimite5 { get; set; }
        public Nullable<decimal> TariffaLimite5 { get; set; }
        public Nullable<int> KgLimite6 { get; set; }
        public Nullable<decimal> TariffaLimite6 { get; set; }
        public Nullable<int> KgLimite7 { get; set; }
        public Nullable<decimal> TariffaLimite7 { get; set; }
        public Nullable<bool> DisponibileOnline { get; set; }
        public string Label { get; set; }
        public string PathTrack { get; set; }
        public Nullable<int> Disattivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordini> Ordini { get; set; }
    }
}
