//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_listinobase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_listinobase()
        {
            this.Ordini = new HashSet<Ordini>();
        }
    
        public int IdListinoBase { get; set; }
        public string Nome { get; set; }
        public Nullable<int> IdCurvaAtt { get; set; }
        public Nullable<int> IdCurvaPubbl { get; set; }
        public Nullable<int> IdFormProd { get; set; }
        public Nullable<int> IdFormato { get; set; }
        public Nullable<int> IdTipoCartaCop { get; set; }
        public Nullable<int> IdTipoCarta { get; set; }
        public Nullable<int> IdTipoCartaDorso { get; set; }
        public Nullable<int> IdPrev { get; set; }
        public Nullable<int> IdColoreStampa { get; set; }
        public Nullable<decimal> v1 { get; set; }
        public Nullable<decimal> v2 { get; set; }
        public Nullable<decimal> v3 { get; set; }
        public Nullable<decimal> v4 { get; set; }
        public Nullable<decimal> v5 { get; set; }
        public Nullable<decimal> v6 { get; set; }
        public Nullable<float> qta1 { get; set; }
        public Nullable<float> qta2 { get; set; }
        public Nullable<float> qta3 { get; set; }
        public Nullable<float> qta4 { get; set; }
        public Nullable<float> qta5 { get; set; }
        public Nullable<float> qta6 { get; set; }
        public Nullable<float> p1 { get; set; }
        public Nullable<float> p2 { get; set; }
        public Nullable<float> p3 { get; set; }
        public Nullable<float> p4 { get; set; }
        public Nullable<float> p5 { get; set; }
        public Nullable<float> p6 { get; set; }
        public Nullable<int> qtacollo { get; set; }
        public Nullable<int> faccmin { get; set; }
        public Nullable<int> faccmax { get; set; }
        public string imgrif { get; set; }
        public Nullable<bool> nofaccsuimpianti { get; set; }
        public Nullable<short> Disattivo { get; set; }
        public Nullable<int> MultiploQta { get; set; }
        public Nullable<short> noResa { get; set; }
        public Nullable<int> PercAdatCostoCopia { get; set; }
        public Nullable<int> AvviamStampa { get; set; }
        public Nullable<int> MinimaleStampa { get; set; }
        public string ImgSito { get; set; }
        public Nullable<int> PrendiIcoDa { get; set; }
        public Nullable<int> TipoPrezzo { get; set; }
        public string DescrSito { get; set; }
        public Nullable<int> LastUpdate { get; set; }
        public Nullable<int> IdTipoImballo { get; set; }
        public Nullable<int> IdModelloCubetto { get; set; }
        public string GoogleDescr { get; set; }
        public string GoogleSEO { get; set; }
        public Nullable<int> MoltiplicatoreQta { get; set; }
        public Nullable<int> InEvidenza { get; set; }
        public Nullable<int> Ordinamento { get; set; }
        public Nullable<int> NascondiOnline { get; set; }
        public string LabelWeb { get; set; }
        public string NomeInterno { get; set; }
        public string LargRotolo { get; set; }
        public Nullable<int> QtaDefault { get; set; }
        public Nullable<int> MostraPrezziTabella { get; set; }
        public Nullable<int> IdHotFolderPostRefine { get; set; }
        public Nullable<int> CalcolaAncheDaSolo { get; set; }
        public Nullable<int> IdMacchinarioProduzione { get; set; }
        public Nullable<int> IdMacchinarioTaglio { get; set; }
        public Nullable<int> TipoControlloPrezzo { get; set; }
        public Nullable<int> DefaultNFogli { get; set; }
        public Nullable<int> VMotoreCalcolo { get; set; }
        public Nullable<int> PercPromoAutomatico { get; set; }
        public Nullable<int> PercMaxPromoFatturato { get; set; }
        public Nullable<int> MoltiplicatoreQta2 { get; set; }
        public Nullable<int> MoltiplicatoreQta3 { get; set; }
        public Nullable<int> MoltiplicatoreQta4 { get; set; }
        public Nullable<int> MoltiplicatoreQta5 { get; set; }
        public Nullable<int> AbilitaQtaIntermedie { get; set; }
        public Nullable<int> AbilitaQtaSottoColonna1 { get; set; }
        public Nullable<int> MoltiplicatoreQta0 { get; set; }
        public Nullable<int> MoltiplicatoreQtaIntermedia { get; set; }
        public Nullable<int> IdMacchinarioProduzione2 { get; set; }
        public Nullable<int> AvviamStampa2 { get; set; }
        public Nullable<int> MinimaleStampa2 { get; set; }
        public Nullable<int> IdFormatoMacchina2 { get; set; }
        public Nullable<int> IsFormerChoice { get; set; }
        public Nullable<int> IdListinoBaseSource { get; set; }
        public string PrefissoVarianti { get; set; }
        public Nullable<int> NoAttachFile { get; set; }
        public Nullable<int> ConSoggettiDuplicati { get; set; }
        public Nullable<int> idGruppoLogico { get; set; }
        public Nullable<int> IdGruppoListiniConsigliati { get; set; }
        public Nullable<int> IdGruppoLCAppartenenza { get; set; }
        public Nullable<int> AllowCustomSize { get; set; }
        public Nullable<int> IdLavTaglioSoggetti { get; set; }
        public Nullable<int> IdLavTaglioDuplicati { get; set; }
        public Nullable<int> AttivaPromoAutomatico { get; set; }
        public Nullable<int> CounterDayPromo { get; set; }
        public string IdZoho { get; set; }
        public Nullable<int> DisattivaAccessoSito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordini> Ordini { get; set; }
    }
}
