//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Collections.Generic;
    
    public partial class tokens
    {
        public int Id { get; set; }
        public string Token_Refresh { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Token_Work { get; set; }
    }
}
