//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithPostman
{
    using System;
    using System.Collections.Generic;
    
    public partial class tokens
    {
        public int Id { get; set; }
        public string Token_Refresh { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Token_Work { get; set; }
    }
}
